#!/bin/bash

rm -rf CMakeCache.txt CMakeFiles

if [ "$1" = "gdb" ]; then
	cmake -DTOPC_USE=1 -DTOPC_USE_SEQ=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-std=c++11  ./
	make clean
	make -j4
	gdb convertMCNPToG4NDL

elif [ "$1" = "valgrind" ]; then
	cmake -DTOPC_USE=1 -DTOPC_USE_SEQ=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-std=c++11 ./
	make clean
	make -j4
	valgrind --leak-check=full --show-reachable=yes --error-limit=no --track-origins=yes --log-file=convMCNP.log ./convertMCNPToG4NDL $2 $3 $4

else
	cmake -DTOPC_USE=1 -DTOPC_USE_SEQ=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-std=c++11 ./
	make clean
	make -j4
	./convertMCNPToG4NDL $1 $2 $3

fi
